services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 hfps_tic.wsgi:application
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3  # Mount SQLite DB
    ports:
      - "8000:8000"
    env_file:
      - .env
