databases:
  - name: hfps_tic_db
    databaseName: hfps_tic
    user: hfps_tic_user

services:
  - type: web
    name: hfps_tic
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn hfps_tic.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hfps_tic_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
